import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import PokemonList from "@/components/pokemonList";

export default function Home() {
  return (
    <>
      <Head>
        <title>PokeWiki</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/pokeball.png" />
      </Head>
      <main className={styles.Main}>
        <PokemonList />
      </main>
    </>
  );
}
