import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import FiltersComponent from "@/components/filtersComponent";
import BigPokemonCard from "@/components/bigPokemonCard";
import { useState } from "react";

export default function Home() {
  const [pokemonID, setPokemonID] = useState(null);

  return (
    <>
      <Head>
        <title>PokeWiki</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/pokeball.png" />
      </Head>
      <main className={styles.Main}>
        <FiltersComponent setPokemonID={setPokemonID} />
        {!pokemonID ? (
          <div>nothing</div>
        ) : (
          <BigPokemonCard pokemonID={pokemonID} />
        )}
      </main>
    </>
  );
}
